[package]
name = "steelwool"
version = "0.2.0"
edition = "2024"
license = "LGPL-3.0-or-later"
repository = "https://github.com/georgesleen/steelwool"
description = "Opinionated formatter for Steel"

[dependencies]
steel-parser = { git = "https://github.com/mattwparas/steel.git", rev = "1b785a4e9d24e3553b242522b35d4498dae72816" }
toml = "1"

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std", "bit-set", "fork", "timeout"] }
steel-parser = { git = "https://github.com/mattwparas/steel.git", rev = "1b785a4e9d24e3553b242522b35d4498dae72816" }
